name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8, 11, 17, 21 ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: liberica
          cache: maven
      - name: Build with Maven
        run: mvn -V -B package